[mypy]
python_version = 3.8
warn_unused_configs = True

[mypy-qat.*]
ignore_missing_imports = True

[mypy-parameterized]
ignore_missing_imports = True

[mypy-numpy]
ignore_missing_imports = True

[mypy-isdclassic.*]
ignore_missing_imports = True
